export const listOfChassis = [
  {
    id: 0,
    imgUrl: "/src/assets/images/Mule.jpg",
    chassis: "Mule",
    stats: {
      structurepoints: 12,
      energypoints: 4,
      heatcap: 6,
      systemslots: 16,
      moduleslots: 2,
      cargocap: 16,
      techlevel: 1,
      salvagevalue: 7,
    },
  },
  {
    id: 1,
    imgUrl: "/src/assets/images/Mazona.jpg",
    chassis: "Mazona",
    stats: {
      structurepoints: 5,
      energypoints: 10,
      heatcap: 6,
      systemslots: 7,
      moduleslots: 3,
      cargocap: 6,
      techlevel: 1,
      salvagevalue: 4,
    },
  },
  {
    id: 2,
    imgUrl: "/src/assets/images/Scrapper.jpg",
    chassis: "Scrapper",
    stats: {
      structurepoints: 9,
      energypoints: 9,
      heatcap: 8,
      systemslots: 12,
      moduleslots: 2,
      cargocap: 6,
      techlevel: 1,
      salvagevalue: 6,
    },
  },
  {
    id: 3,
    imgUrl: "/src/assets/images/Spectrum.jpg",
    chassis: "Spectrum",
    stats: {
      structurepoints: 17,
      energypoints: 11,
      heatcap: 3,
      systemslots: 7,
      moduleslots: 4,
      cargocap: 6,
      techlevel: 1,
      salvagevalue: 10,
    },
  },
  {
    id: 4,
    imgUrl: "/src/assets/images/Thresher.jpg",
    chassis: "Thresher",
    stats: {
      structurepoints: 15,
      energypoints: 6,
      heatcap: 10,
      systemslots: 9,
      moduleslots: 2,
      cargocap: 6,
      techlevel: 1,
      salvagevalue: 9,
    },
  },
];
